apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobrunners.myorg.io
spec:
  group: myorg.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                command:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: jobrunners
    singular: jobrunner
    kind: JobRunner
    shortNames:
      - jr
